version: '2'

services:
  vm-store:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=vm
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
  vm-agent:
    depends_on:
      - "vm-store"
      - "kafka"
    image: cloudiator/vm-agent:latest
    restart: always
    environment:
      - JPA_USER=${DATABASE_USER}
      - JPA_PASSWORD=${DATABASE_PASSWORD}
      - JPA_DATABASE=vm
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JPA_HOST=vm-store
  node-store:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=node
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
  node-agent:
    depends_on:
      - "node-store"
      - "kafka"
    image: cloudiator/node-agent:latest
    restart: always
    environment:
      - JPA_USER=${DATABASE_USER}
      - JPA_PASSWORD=${DATABASE_PASSWORD}
      - JPA_DATABASE=node
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JPA_HOST=node-store
  discovery-store:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=discovery
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
  discovery-agent:
    depends_on:
      - "discovery-store"
      - "kafka"
    image: cloudiator/discovery-agent:latest
    restart: always
    environment:
      - JPA_USER=${DATABASE_USER}
      - JPA_PASSWORD=${DATABASE_PASSWORD}
      - JPA_DATABASE=discovery
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JPA_HOST=discovery-store
  matchmaking-agent:
    depends_on:
      - "kafka"
    image: cloudiator/matchmaking-agent:latest
    restart: always
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  job-store:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=job
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
  job-agent:
    depends_on:
      - "job-store"
      - "kafka"
    image: cloudiator/job-agent:latest
    restart: always
    environment:
      - JPA_USER=${DATABASE_USER}
      - JPA_PASSWORD=${DATABASE_PASSWORD}
      - JPA_DATABASE=job
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JPA_HOST=job-store
  user-store:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=user
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
  user-agent:
    depends_on:
      - "user-store"
      - "kafka"
    image: cloudiator/user-agent:latest
    restart: always
    environment:
      - JPA_USER=${DATABASE_USER}
      - JPA_PASSWORD=${DATABASE_PASSWORD}
      - JPA_DATABASE=user
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JPA_HOST=user-store
      - AUTH_MODE=${AUTH_MODE}
      - AUTH_TOKEN=${AUTH_TOKEN}
  rest-server:
    depends_on:
      - "kafka"
    image: cloudiator/rest-server:latest
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SECURITY_API_KEY
    ports:
      - 9000:9000
  kafka:
    image: spotify/kafka
    restart: always
  kafka-manager:
    depends_on:
      - "kafka"
    image: sheepkiller/kafka-manager:latest
    environment:
      - ZK_HOSTS=kafka:2181
      - APPLICATION_SECRET=verySecureSecret
      - KM_VERSION=1.3.3.17
    ports:
      - 8080:9000
    volumes:
      - ./kafka-manager:/kafka-manager-1.3.1.8/conf
    
