version: '2'

services:
  vm-store:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=vm
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
  vm-agent:
    depends_on:
      - "vm-store"
      - "kafka"
    image: cloudiator/vm-agent:latest
    restart: always
    environment:
      - JPA_USER=${DATABASE_USER}
      - JPA_PASSWORD=${DATABASE_PASSWORD}
      - JPA_DATABASE=vm
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JPA_HOST=vm-store
      - LOGSTASH_HOST=logstash:5000
  node-store:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=node
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
  node-agent:
    depends_on:
      - "node-store"
      - "kafka"
    image: cloudiator/node-agent:latest
    restart: always
    environment:
      - JPA_USER=${DATABASE_USER}
      - JPA_PASSWORD=${DATABASE_PASSWORD}
      - JPA_DATABASE=node
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JPA_HOST=node-store
      - LOGSTASH_HOST=logstash:5000
  discovery-store:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=discovery
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
  discovery-agent:
    depends_on:
      - "discovery-store"
      - "user-agent"
      - "kafka"
    image: cloudiator/discovery-agent:latest
    restart: always
    environment:
      - JPA_USER=${DATABASE_USER}
      - JPA_PASSWORD=${DATABASE_PASSWORD}
      - JPA_DATABASE=discovery
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JPA_HOST=discovery-store
  install-agent:
    depends_on:
      - "kafka"
    image: cloudiator/install-agent:latest
    restart: always
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - LOGSTASH_HOST=logstash:5000
  matchmaking-agent:
    depends_on:
      - "kafka"
    image: cloudiator/matchmaking-agent:latest
    restart: always
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - LOGSTASH_HOST=logstash:5000
  job-store:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=job
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
  job-agent:
    depends_on:
      - "job-store"
      - "kafka"
    image: cloudiator/job-agent:latest
    restart: always
    environment:
      - JPA_USER=${DATABASE_USER}
      - JPA_PASSWORD=${DATABASE_PASSWORD}
      - JPA_DATABASE=job
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JPA_HOST=job-store
  scheduler-agent:
    depends_on:
      - "kafka"
    image: cloudiator/scheduler-agent:latest
    restart: always
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  lance-agent:
      depends_on:
        - "kafka"
      image: cloudiator/lance-agent:latest
      restart: always
      environment:
        - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
        - ETCD_HOST=${HOST_IP}
  user-store:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=user
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
  user-agent:
    depends_on:
      - "user-store"
      - "kafka"
    image: cloudiator/user-agent:latest
    restart: always
    environment:
      - JPA_USER=${DATABASE_USER}
      - JPA_PASSWORD=${DATABASE_PASSWORD}
      - JPA_DATABASE=user
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JPA_HOST=user-store
      - AUTH_MODE=${AUTH_MODE}
      - AUTH_TOKEN=${AUTH_TOKEN}
  rest-server:
    depends_on:
      - "kafka"
    image: cloudiator/rest-server:latest
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - LOGSTASH_HOST=logstash:5000
    ports:
      - 9000:9000
  encryption-agent:
    depends_on:
      - "kafka"
    image: cloudiator/encryption-agent:latest
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  etcd:
    image: quay.io/coreos/etcd
    ports:
      - 4001:4001
      - 2380:2380
      - 2379:2379
    environment:
      - ETCD_NAME=etcd0
      - ETCD_ADVERTISE_CLIENT_URLS=http://${HOST_IP}:2379,http://${HOST_IP}:4001
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${HOST_IP}:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd0=http://${HOST_IP}:2380

  etcd-browser:
    build: ./etcd-browser
    ports:
      - 8000:8000
    environment:
      ETCD_HOST: etcd
      ETCD_PORT: 2379
    depends_on:
      - "etcd"

  kafka:
    image: spotify/kafka
    restart: always
  kafka-manager:
    depends_on:
      - "kafka"
    image: sheepkiller/kafka-manager:latest
    environment:
      - ZK_HOSTS=kafka:2181
      - APPLICATION_SECRET=verySecureSecret
      - KM_VERSION=1.3.3.17
    ports:
      - 8080:9000
    volumes:
      - ./kafka-manager:/kafka-manager-1.3.1.8/conf
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    
